POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "I have friends on here somewhere I swear",
    "author": "Rippen Gaye",
    "url": "#",
    "likes": "2"
}
###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "Thatp",
    "name": "Phashiii",
    "password": "00aa"
}
###
GET http://localhost:3003/api/users